### ISSUE TITLE
一些意见

### ISSUE THREAD

**Issue by Nenot233** [sophisticate9008/draw_wife#3]
希望能添加开启金币抽，设置金币抽，机器人管理员设置你的老婆。

**Comment by Nenot233** [comment]
还有一些抽到重复的老婆，可以提示一下抽到过几次

**Comment by sophisticate9008** [comment]
> 希望能添加开启金币抽，设置金币抽，机器人管理员设置你的老婆。

这不和我方舟那个一样了吗，缺的是其他方面的创意，光一个at太少了，nb商店里的透似乎又没有表现力，

**Comment by Nenot233** [comment]
主要是，这个插件十几个群天天在抽，我想用金币去限制一下，一周调用接近7000

**Comment by sophisticate9008** [comment]
暂时先用真寻自带插件控制先管着吧

**Comment by Nenot233** [comment]
可以写一个抢老婆)

**Comment by Nenot233** [comment]
例如，1的老婆是2,3的指令是抢老婆@1，这样有概率抢过来

**Comment by sophisticate9008** [comment]
感谢你的意见 ，但是ntr版已经有了，在nb商店里
说实话，得知nb有相同的我已经放弃了这个插件

**Comment by Nenot233** [comment]
但是，挺喜欢你写的这个插件

**Comment by sophisticate9008** [comment]
> 但是，挺喜欢你写的这个插件
加了一些功能
