### ISSUE TITLE
除了海王榜，整个群名媛榜，看谁被抽次数多（

### ISSUE THREAD

**Issue by gagadaxiao** [sophisticate9008/draw_wife#7]

**Comment by sophisticate9008** [comment]
应该检查下真寻\services\db_context.py？

**Comment by sophisticate9008** [comment]
试着换一下顺序变成
from tortoise import fields
from services.db_context import Model

**Comment by gagadaxiao** [comment]
谢谢回复，我的真寻/services/db_context.py里没有Model相关的功能。刚才清华源安装的tortoise导入fields也报错
ImportError: cannot import name 'fields' from 'tortoise' (C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-RTGWc6IX-py3.10\lib\site-packages\tortoise\__init__.py)

**Comment by sophisticate9008** [comment]
要安装tortoise-rom

**Comment by gagadaxiao** [comment]
谢谢回复。import fields没问题了。从db_context.py导入Model还是报错。请问db_context.py文件有更新方式吗？可能和你的不是一个版本了。这是该文件全文
![无标题](https://user-images.githubusercontent.com/68414286/224011233-3160cb6d-4ae2-40c6-a2b2-4f429ab0b69d.png)

**Comment by sophisticate9008** [comment]
我之前也是不完全更新最后手动下的包覆盖的
