### ISSUE TITLE
拟造老婆报错

### ISSUE THREAD

**Issue by PackageInstaller** [sophisticate9008/draw_wife#9]
如图
![Screenshot_20230326_135255](https://user-images.githubusercontent.com/80018096/227757998-c198d729-dc3d-4faf-91e4-dea9725a33d8.png)

**Comment by PackageInstaller** [comment]
抽群老婆都报错，我直接麻了
![image](https://user-images.githubusercontent.com/80018096/227759020-c766b8aa-3216-4fee-b317-c040351165f1.png)

**Comment by sophisticate9008** [comment]
我母鸡啊，到时候帮你问问chatgpt

**Comment by PackageInstaller** [comment]
就是问了也不知道才来的啊

**Comment by sophisticate9008** [comment]
> 就是问了也不知道才来的啊

![-22d9ed712846f08](https://user-images.githubusercontent.com/94435821/227854504-9a6ea01b-689e-46fb-a148-3ac107d22399.jpg)

**Comment by sophisticate9008** [comment]
你这好像就是阿咪说的那个初次签到用道具报错那个

**Comment by PackageInstaller** [comment]
[已解决](https://github.com/HibiKier/zhenxun_bot/issues/1321#issuecomment-1506522000)
